BASIC EX CONVERTING WORD TO VEC


In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5806, 8481, 3961, 1523],
 [5806, 8481, 3961, 8301],
 [5806, 9140, 3961, 5153],
 [8787, 2425, 8840, 7607, 1727],
 [8787, 2425, 8840, 7607, 1703],
 [8023, 5806, 1292, 3961, 1985],
 [5460, 1108, 7559, 7607]]

In [10]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [14]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5806 8481 3961 1523]
 [   0    0    0    0 5806 8481 3961 8301]
 [   0    0    0    0 5806 9140 3961 5153]
 [   0    0    0 8787 2425 8840 7607 1727]
 [   0    0    0 8787 2425 8840 7607 1703]
 [   0    0    0 8023 5806 1292 3961 1985]
 [   0    0    0    0 5460 1108 7559 7607]]


In [15]:
## feature representation
dim=10

In [16]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 201ms/step


array([[[-0.04037889, -0.03481871, -0.01463305,  0.0031089 ,
         -0.01124258, -0.00296561, -0.04667624,  0.01960713,
          0.04920932, -0.04895827],
        [-0.04037889, -0.03481871, -0.01463305,  0.0031089 ,
         -0.01124258, -0.00296561, -0.04667624,  0.01960713,
          0.04920932, -0.04895827],
        [-0.04037889, -0.03481871, -0.01463305,  0.0031089 ,
         -0.01124258, -0.00296561, -0.04667624,  0.01960713,
          0.04920932, -0.04895827],
        [-0.04037889, -0.03481871, -0.01463305,  0.0031089 ,
         -0.01124258, -0.00296561, -0.04667624,  0.01960713,
          0.04920932, -0.04895827],
        [ 0.0475913 ,  0.04206541,  0.02753634,  0.04896642,
         -0.02149764,  0.01713873, -0.03955992, -0.02600667,
         -0.04691125,  0.00699301],
        [-0.02867409, -0.02655672,  0.01306338,  0.04084461,
         -0.02058498,  0.00690837, -0.03538578, -0.02412765,
          0.03271114, -0.02909497],
        [-0.04267269, -0.00990982,  0.01152105, -0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 5806, 8481, 3961, 1523])

In [20]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 45ms/step


array([[-0.04037889, -0.03481871, -0.01463305,  0.0031089 , -0.01124258,
        -0.00296561, -0.04667624,  0.01960713,  0.04920932, -0.04895827],
       [-0.04037889, -0.03481871, -0.01463305,  0.0031089 , -0.01124258,
        -0.00296561, -0.04667624,  0.01960713,  0.04920932, -0.04895827],
       [-0.04037889, -0.03481871, -0.01463305,  0.0031089 , -0.01124258,
        -0.00296561, -0.04667624,  0.01960713,  0.04920932, -0.04895827],
       [-0.04037889, -0.03481871, -0.01463305,  0.0031089 , -0.01124258,
        -0.00296561, -0.04667624,  0.01960713,  0.04920932, -0.04895827],
       [ 0.0475913 ,  0.04206541,  0.02753634,  0.04896642, -0.02149764,
         0.01713873, -0.03955992, -0.02600667, -0.04691125,  0.00699301],
       [-0.02867409, -0.02655672,  0.01306338,  0.04084461, -0.02058498,
         0.00690837, -0.03538578, -0.02412765,  0.03271114, -0.02909497],
       [-0.04267269, -0.00990982,  0.01152105, -0.04877431,  0.00038512,
        -0.03852904, -0.00466241, -0.04496066